### ISSUE TITLE
Casatune Questions

### ISSUE THREAD

**Issue by bigmack48** [jonkristian/casatunes#1]
I using russound thru Casatunes

I cannot get the Text to speak to work. (using TTS Support to send custom text using http: note in casatunes doc)

example: this play doorbell charm

http://xxx.xxx.x.xxx:8735/api/v1/system/doorbell/zones/study?volume=80

Thank you 

Greg

**Comment by jonkristian** [comment]
Have you tried opening that url in your browser? It should be a simple get request, so you should be able to debug through that. I have a doorbell set up like this:
```
rest_command:
  doorbell:
    url: "http://192.168.1.149:8735/api/v1/system/doorbell/chimes/dingdong"
    method: get
    payload: "volume=35"
```
